## Crear imagen de la aplicacion
## docker build -f src/main/docker/Dockerfile.jvm -t app-customers .
## docker build -f src/main/docker/Dockerfile.jvm -t pablofernandosimbana/app-customers .
## docker login
## docker push pablofernandosimbana/app-customers
## docker logout
FROM eclipse-temurin:25.0.3_9-jre-alpine

ENV LANGUAGE='en_US:en'

RUN mkdir /app
WORKDIR /app

COPY build/libs/app-customers-0.0.1-SNAPSHOT.jar app.jar

CMD ["java","-jar","app.jar"]