## Crear imagen de la aplicacion
## docker build -f src/main/docker/Dockerfile.jvm -t app-authors .
## docker build -f src/main/docker/Dockerfile.jvm -t pablofernandosimbana/app-authors .
## docker login
## docker push pablofernandosimbana/app-authors
FROM eclipse-temurin:25.0.3_9-jre-alpine

ENV LANGUAGE='en_US:en'

RUN mkdir /app
WORKDIR /app

#RUN apk update
#RUN apk add curl

COPY build/quarkus-app/lib ./lib
COPY build/quarkus-app/quarkus ./quarkus
COPY build/quarkus-app/app ./app
COPY build/quarkus-app/quarkus-run.jar app.jar

CMD ["java","-jar","app.jar"]