quarkus.datasource.db-kind=postgresql
# Si se quita toda la configuracion se crea la base en docker
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books2026
quarkus.datasource.username=postgres
quarkus.datasource.password=587621

#quarkus.flyway.actions=true
#quarkus.flyway.baseline-at-migrate=true
#quarkus.flyway.migrate-at-start=true
quarkus.flyway.migrate-at-start=true
app.title=Authors Q
#quarkus.package.jar.type=uber-jar