CREATE TABLE authors
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (nombre) values ('Pablo Simbaña');
insert into authors (nombre) values ('Jorge Nitales');
insert into authors (nombre) values ('Moises Caicedo');
insert into authors (nombre) values ('William Pacho');

select * from authors;