CREATE TABLE authors
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    version INTEGER,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (name) values ('Pablo Simbaña');
insert into authors (name) values ('Jorge Nitales');
insert into authors (name) values ('Moises Caicedo');
insert into authors (name) values ('William Pacho');