CREATE TABLE customers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(255),
    name    VARCHAR(255),
    version INTEGER,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE purcharse_orders
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id INTEGER,
    deliveredor TIMESTAMP WITHOUT TIME ZONE,
    placedon    TIMESTAMP WITHOUT TIME ZONE,
    status      INTEGER,
    total       INTEGER,
    CONSTRAINT pk_purcharse_orders PRIMARY KEY (id)
);

ALTER TABLE purcharse_orders
    ADD CONSTRAINT FK_PURCHARSE_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

CREATE TABLE "line-items"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id INTEGER,
    quantity INTEGER,
    isbn     VARCHAR(255),
    CONSTRAINT "pk_line-items" PRIMARY KEY (id)
);

ALTER TABLE "line-items"
    ADD CONSTRAINT "FK_LINE-ITEMS_ON_ORDER" FOREIGN KEY (order_id) REFERENCES purcharse_orders (id);